# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_arxiv_pdf_url": "00_core.ipynb",
         "download_file": "00_core.ipynb",
         "is_url": "00_core.ipynb",
         "TargetType": "00_core.ipynb",
         "Target": "00_core.ipynb",
         "MessageEncoded": "01_mail.ipynb",
         "SCOPES": "01_mail.ipynb",
         "Emailer": "01_mail.ipynb"}

modules = ["core.py",
           "utils.py",
           "mail.py"]

doc_url = "https://fastai.github.io/send_to_pb/"

git_url = "https://github.com/fastai/send_to_pb/tree/master/"

def custom_doc_links(name): return None
