# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_cli.ipynb (unless otherwise specified).

__all__ = ['send_to_pocketbook']

# Cell
import pathlib
import click

from .core import Target
from .mail import Emailer

# Cell

@click.command()
@click.argument('location', nargs=1)
def send_to_pocketbook(location):
    """Send file from location to pocketbook"""
    t = Target(location)
    t.fetch_target()
    Emailer().send_file(to="david.dobrinskiy@gmail.com",
                        file=t.fetched_path,
                 )

