# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_utils.ipynb (unless otherwise specified).

__all__ = []

# Cell
import sys
from loguru import logger
logger.remove()
# logger.add('../logs/logs.txt', level="DEBUG")
logger.add(sys.stderr,enqueue=True, level="DEBUG")
# logger.add(sys.stderr,enqueue=True, level="INFO")